services:
    _defaults:
        public: true
        autowire: true

    emmedy_h5p.options:
        class: Emmedy\H5PBundle\Core\H5POptions
        arguments: [~, '%kernel.project_dir%']

    Emmedy\H5PBundle\Core\H5POptions:
        arguments: [~, '%kernel.project_dir%']

    emmedy_h5p.editor_storage:
        class: Emmedy\H5PBundle\Editor\EditorStorage

    Emmedy\H5PBundle\Editor\EditorStorage:
    H5peditorStorage: '@emmedy_h5p.editor_storage'

    emmedy_h5p.interface:
        class: Emmedy\H5PBundle\Core\H5PSymfony

    H5PFrameworkInterface: '@emmedy_h5p.interface'

    emmedy_h5p.core:
        class: H5PCore
    H5PCore: '@emmedy_h5p.core'

    emmedy_h5p.editor_ajax:
        class: Emmedy\H5PBundle\Editor\EditorAjax

    Emmedy\H5PBundle\Editor\EditorAjax:

    H5PEditorAjaxInterface: '@emmedy_h5p.editor_ajax'

    emmedy_h5p.editor:
        class: H5peditor

    H5peditor: '@emmedy_h5p.editor'

    emmedy_h5p.validator:
        class: H5PValidator

    emmedy_h5p.storage:
        class: H5PStorage
    H5PStorage: '@emmedy_h5p.storage'

    emmedy_h5p.contentvalidator:
        class: H5PContentValidator

    H5PContentValidator: '@emmedy_h5p.contentvalidator'

    emmedy_h5p.export:
        class: H5PExport

    emmedy_h5p.integration:
        class: Emmedy\H5PBundle\Core\H5PIntegration

    Emmedy\H5PBundle\Core\H5PIntegration: '@emmedy_h5p.integration'

    emmedy_h5p.library_storage:
        class: Emmedy\H5PBundle\Editor\LibraryStorage

    LibraryStorage: '@emmedy_h5p.library_storage'

    emmedy_h5p.twig.h5p_extension:
        class: Emmedy\H5PBundle\Twig\H5PExtension
        tags:
            - { name: twig.extension }

    H5PExtension: '@emmedy_h5p.twig.h5p_extension'

    Emmedy\H5PBundle\Controller\H5PController:
        tags: [ 'controller.service_arguments' ]